# Generated by Django 5.1.6 on 2025-09-17 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idx", models.PositiveSmallIntegerField(unique=True)),
                ("name", models.CharField(max_length=30)),
                ("short_name", models.CharField(max_length=10)),
                (
                    "testament",
                    models.CharField(
                        choices=[("O", "Ancien"), ("N", "Nouveau")], max_length=1
                    ),
                ),
            ],
            options={
                "ordering": ["idx"],
            },
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField()),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="bible.book",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
                "unique_together": {("book", "number")},
            },
        ),
        migrations.CreateModel(
            name="Verse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField()),
                ("text", models.TextField()),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verses",
                        to="bible.chapter",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
                "unique_together": {("chapter", "number")},
            },
        ),
    ]
