# Generated by Django 5.1.6 on 2025-09-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bible", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
